### ISSUE TITLE
Radio button disabled when only a single option is available.

### ISSUE THREAD

**Issue by robindelaater** [myparcelnl/delivery-options#27]
**Describe the bug**
The delivery options radio button is disabled, but selected, when only one MyParcel option is set. If the user has any other delivery methods besides MyParcel, MyParcel options will always be selected.

**Expected behavior**
Unselect MyParcel shipping method when another delivery method is available.

**Screenshots**
![image](https://user-images.githubusercontent.com/47381559/95723928-01c08300-0c76-11eb-8cfc-956f3f3f1f26.png)

**Comment by robindelaater** [comment]
This happens when home delivery is available.

**Comment by EdieLemoine** [comment]
You're supposed to call `myparcel_disable_delivery_options` when you want to deselect everything. 

### Example
Base state:
<img width="661" alt="Screenshot 2020-10-20 at 12 13 32" src="https://user-images.githubusercontent.com/3886637/96572876-ae7dae80-12cd-11eb-9aad-db3013aa2e98.png">

Call the event:
```js
document.dispatchEvent(new Event('myparcel_disable_delivery_options'));
```

Result:
<img width="308" alt="Screenshot 2020-10-20 at 12 14 19" src="https://user-images.githubusercontent.com/3886637/96572967-cb19e680-12cd-11eb-8dfa-9e819c1ce56e.png">
