### ISSUE TITLE
Pakjegemak locatie lijst niet in juiste volgorde

### ISSUE THREAD

**Issue by phemels** [myparcelnl/delivery-options#37]
Locatie lijst begint niet met dichtstbijzijnde afhaal locatie.

![image](https://user-images.githubusercontent.com/29940263/101389447-bddaaa80-38c1-11eb-93a5-97bee0606308.png)

**Comment by Mitchell-MyParcel** [comment]
@phemels Dit is opgelost in de laatste versie van de Delivery Options. Die versie wordt meegenomen in de release van onze WooCommerce plugin v 4.2.1. die we deze week als pre-release via github gaan delen.
