### ISSUE TITLE
Pickup Locations not visible in Belgium. 

### ISSUE THREAD

**Issue by onlinemusketeers** [myparcelnl/delivery-options#38]
With a clean install. With all the latest versions of WP, WOO and Myparcel (on 7-12-20) it seems that pickup locations are excluded or not loaded on the map for Belgium.
When moving in the map the icon of the locations are visible, but only in The Netherlands.

The list without map works.

![OnPaste 20201207-194314](https://user-images.githubusercontent.com/19552989/101391742-0cd60f00-38c5-11eb-9c9a-b63f476109ea.png)
![OnPaste 20201207-194242](https://user-images.githubusercontent.com/19552989/101391749-0fd0ff80-38c5-11eb-8c06-f45400197215.png)

**Comment by Mitchell-MyParcel** [comment]
@onlinemusketeers This is fixed in the latest version of the Delivery Options. This version wil also be included in WooCommerce 4.2.1. and higher which we will probably pre-release on github this week.
