### ISSUE TITLE
Add active state classes to the list/map buttons to allow styling them

### ISSUE THREAD

**Issue by EdieLemoine** [myparcelnl/delivery-options#62]
**Is your feature request related to a problem? Please describe.**
The buttons 'Lijst' and 'Kaart' don't have an active state for styling them.

**Describe the solution you'd like**
A class to be applied to the buttons when they're active.

From myparcelnl/woocommerce#611

**Comment by brechtwaeghe** [comment]
Hi @EdieLemoine 
I would like to use this feature in the Shopify app. Can you let me know when this will be added?
Thanks
